from argparse import ArgumentParser
import codecs
import copy
import csv
import gc
import random
import os

import numpy as np
from transformers import pipeline
import torch
from tqdm import tqdm


RANDOM_SEED: int = 42


def sample_to_str(source_annotation: str, inv_norm_annotation: str) -> str:
    checked_llm_prediction = ' '.join(inv_norm_annotation.strip().split())
    context = ' '.join(source_annotation.strip().split())
    united_prompt = 'The verified system\'s task is a paraphrase generation.'
    united_prompt += ' The sentence generated by the verified system: '
    united_prompt += checked_llm_prediction
    if united_prompt[-1].isalnum():
        united_prompt += '.'
    united_prompt += f' The generation context: {context}'
    if united_prompt[-1].isalnum():
        united_prompt += '.'
    return united_prompt


def main():
    random.seed(RANDOM_SEED)
    np.random.seed(RANDOM_SEED)
    torch.random.manual_seed(RANDOM_SEED)
    if not torch.cuda.is_available():
        raise RuntimeError('CUDA is not available!')
    torch.cuda.random.manual_seed(RANDOM_SEED)

    parser = ArgumentParser()
    parser.add_argument('-d', '--data', dest='data_name', type=str, required=True,
                        help='The ASR dataset name.')
    parser.add_argument('-m', '--model', dest='detector_name', type=str, required=False,
                        default='bond005/xlm-roberta-xl-hallucination-detector',
                        help='The path to hallucination detector.')
    args = parser.parse_args()

    dataset_dir = os.path.normpath(args.data_name)
    if not os.path.isdir(dataset_dir):
        raise IOError(f'The local directory "{dataset_dir}" does not exist!')
    metadata_fname = os.path.join(dataset_dir, 'metadata.csv')
    if not os.path.isfile(metadata_fname):
        raise IOError(f'The file "{metadata_fname}" does not exist!')

    hallucination_detector = pipeline(
        task='text-classification',
        model=args.detector_name,
        framework='pt', trust_remote_code=True, device='cuda', torch_dtype=torch.float16
    )

    new_rows = []
    with codecs.open(metadata_fname, mode='r', encoding='utf-8', errors='ignore') as fp:
        data_reader = csv.reader(fp, delimiter=',', quotechar='"')
        loaded_header = []
        for row in tqdm(list(filter(lambda it: len(it) > 0, data_reader))):
            if len(loaded_header) == 0:
                loaded_header = copy.copy(row)
                err_msg = f'The file "{metadata_fname}" contains a wrong header!'
                if 'transcription' not in loaded_header:
                    err_msg += f' The "transcription" column is not found in the {loaded_header}.'
                    raise IOError(err_msg)
                if 'inv_normalized_1' not in loaded_header:
                    err_msg += f' The "inv_normalized_1" column is not found in the {loaded_header}.'
                    raise IOError(err_msg)
                if 'inv_normalized_2' not in loaded_header:
                    err_msg += f' The "inv_normalized_2" column is not found in the {loaded_header}.'
                    raise IOError(err_msg)
                new_rows.append(loaded_header + ['hallucination(inv_normalized_1)', 'hallucination(inv_normalized_2)'])
            else:
                err_msg = f'The file "{metadata_fname}" contains a wrong data row!'
                new_source_text = row[loaded_header.index('transcription')].strip()
                new_inv_norm1_text = row[loaded_header.index('inv_normalized_1')].strip()
                new_inv_norm2_text = row[loaded_header.index('inv_normalized_2')].strip()
                if (len(new_source_text) == 0) or (len(new_inv_norm1_text) == 0) or (len(new_inv_norm2_text) == 0):
                    raise IOError(err_msg + f' {row}')
                new_row = copy.copy(row)
                prediction = hallucination_detector(sample_to_str(new_source_text, new_inv_norm1_text))[0]
                predicted_label = prediction['label']
                if predicted_label == 'Hallucination':
                    hallucination_probability = prediction['score']
                else:
                    hallucination_probability = 1.0 - prediction['score']
                new_row.append(f'{round(hallucination_probability, 6)}')
                del prediction, predicted_label, hallucination_probability
                prediction = hallucination_detector(sample_to_str(new_source_text, new_inv_norm2_text))[0]
                predicted_label = prediction['label']
                if predicted_label == 'Hallucination':
                    hallucination_probability = prediction['score']
                else:
                    hallucination_probability = 1.0 - prediction['score']
                new_row.append(f'{round(hallucination_probability, 6)}')
                del prediction, predicted_label, hallucination_probability
                new_rows.append(new_row)
                gc.collect()
                torch.cuda.empty_cache()

    with codecs.open(metadata_fname, mode='w', encoding='utf-8', errors='ignore') as fp:
        data_writer = csv.writer(fp, delimiter=',', quotechar='"')
        for row in new_rows:
            data_writer.writerow(row)
    print(f'{len(new_rows)} rows are successfully processed.')


if __name__ == '__main__':
    main()
